# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/en/latest/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/en/latest/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/en/latest/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#
# install:
#     - pip install -U platformio
#
# script:
#     - platformio run


#
# Template #2: The project is intended to by used as a library with examples
#

# language: python
# python:
#     - "2.7"
#
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"
#
# env:
#     - PLATFORMIO_CI_SRC=path/to/test/file.c
#     - PLATFORMIO_CI_SRC=examples/file.ino
#     - PLATFORMIO_CI_SRC=path/to/test/directory
#
# install:
#     - pip install -U platformio
#
# script:
#     - platformio ci --lib="." --board=TYPE_1 --board=TYPE_2 --board=TYPE_N

language: python
python:
   - "2.7"

sudo: false
cache:
   directories:
       - "~/.platformio"

env:
   - PLATFORMIO_CI_SRC=examples/Blink/Blink.ino

install:
   - pip install -U platformio

   - wget https://github.com/scottdky/Streaming/archive/master.zip -O /tmp/Streaming.zip
   - unzip /tmp/Streaming.zip -d /tmp/

   - wget https://github.com/nettigo/Assert4a/archive/master.zip -O /tmp/Assert4a.zip
   - unzip /tmp/Assert4a.zip -d /tmp/

   - wget https://github.com/adafruit/Adafruit-GFX-Library/archive/master.zip -O /tmp/Adafruit-GFX-Library-master.zip
   - unzip /tmp/Adafruit-GFX-Library-master.zip -d /tmp/

   - wget https://github.com/neu-rah/PCINT/archive/master.zip -O /tmp/PCINT-master.zip
   - unzip /tmp/PCINT-master.zip -d /tmp/

   - wget https://github.com/olikraus/U8glib_Arduino/archive/master.zip -O /tmp/U8glib_Arduino-master.zip
   - unzip /tmp/U8glib_Arduino-master.zip -d /tmp/

   - wget https://github.com/neu-rah/AnsiStream/archive/master.zip -O /tmp/AnsiStream-master.zip
   - unzip /tmp/AnsiStream-master.zip -d /tmp/

   - wget https://bitbucket.org/fmalpartida/new-liquidcrystal/downloads/NewliquidCrystal_1.3.4.zip -O /tmp/NewliquidCrystal_1.3.4.zip
   - unzip /tmp/NewliquidCrystal_1.3.4.zip -d /tmp/

script:
   - platformio ci --lib="." --lib="/tmp/Streaming-master" --lib="/tmp/Assert4a-master" --lib="/tmp/Adafruit-GFX-Library-master" --lib="/tmp/PCINT-master" --lib="/tmp/U8glib_Arduino-master" --lib="/tmp/AnsiStream-master" --lib="NewliquidCrystal" --board=nanoatmega328
